import { CustomerLifecycleState } from '@click-india/shared-types';
import { eventBus } from '@click-india/shared-events';
import { createClient } from '@supabase/supabase-js';

export class NotificationService {
  private supabase;

  constructor(url: string, key: string) {
    this.supabase = createClient(url, key);
  }

  public async dispatchLifecycleNotification(
    customerId: string, 
    state: CustomerLifecycleState,
    urgency: number
  ): Promise<void> {
    const templates: Record<CustomerLifecycleState, string> = {
      'NEW_ENQUIRY': 'Welcome to Click Capital! Our AI is preparing your financial diagnosis.',
      'HIGH_STRESS_CUSTOMER': 'Urgent: We have prioritized your case for immediate debt relief.',
      'CONSULTATION_ACTIVE': 'Your consultation is scheduled. Please ensure documents are ready.',
      'BLUEPRINT_IN_PROGRESS': 'Your Strategy Blueprint is being generated by our specialists.',
      'EXECUTION_STAGE': 'Execution in progress. Track your disbursement status in the app.',
      'REFINANCE_CANDIDATE': 'Good news! You are eligible for a lower-interest refinance.',
      'RETENTION_RISK': 'We noticed you have been inactive. Is there anything we can help with?',
      'MARKETPLACE_ELIGIBLE': 'New opportunity identified! Your asset is now eligible for the marketplace.',
      'LONG_TERM_RELATIONSHIP': 'Thank you for trusting us. Check out your updated savings roadmap.',
    };

    const message = templates[state] || 'Update from Click Capital regarding your application.';

    // 1. Persist to Database
    const { error } = await this.supabase
      .from('notifications')
      .insert([{
        user_id: customerId,
        title: state.replace(/_/g, ' '),
        message: message,
        notification_type: 'LIFECYCLE',
        read_status: false
      }]);

    if (error) console.error('[NOTIFICATION_ERROR]', error);

    // 2. Multi-channel simulation (Logs)
    console.log(`[MULTI-CHANNEL DISPATCH] 
      TO: ${customerId}
      SMS: ${message}
      EMAIL: Sent via simulated transport
      WHATSAPP: Sent via simulated gateway`);

    // 3. Emit for real-time UI
    eventBus.emit({
      type: 'NotificationTriggered',
      actor: { id: 'SYSTEM', type: 'SYSTEM' },
      payload: { customerId, state, message, urgency },
    });
  }

  public async dispatchOperationalAlert(
    type: 'NEW_LEAD' | 'PAYMENT_SUBMITTED' | 'CONSULTATION_MISSED' | 'ESCALATION',
    message: string,
    metadata: any = {}
  ): Promise<void> {
    // 1. Persist to Database (Targeting Admins/Operators)
    // In a real system, we might query all admin IDs or use a specific role-based channel
    const { error } = await this.supabase
      .from('notifications')
      .insert([{
        title: `OPERATIONAL: ${type.replace(/_/g, ' ')}`,
        message: message,
        notification_type: 'OPERATIONAL',
        read_status: false,
        metadata: metadata
      }]);

    if (error) console.error('[OPERATIONAL_ALERT_ERROR]', error);

    // 2. Emit for real-time CRM UI
    eventBus.emit({
      type: 'OperationalAlertTriggered',
      actor: { id: 'SYSTEM', type: 'SYSTEM' },
      payload: { type, message, metadata },
    });

    // 3. Simulated Admin Channels (WhatsApp/Push)
    console.log(`[OPERATIONAL_ALERT] ${type}: ${message}`);
  }
}
