import { LeadStatus, CustomerLifecycleState } from '@click-india/shared-types';

export const VALID_LEAD_TRANSITIONS: Record<LeadStatus, LeadStatus[]> = {
  'NEW_LEAD': ['DIAGNOSIS_PENDING', 'REJECTED'],
  'DIAGNOSIS_PENDING': ['CONSULTATION_SCHEDULED', 'REJECTED'],
  'CONSULTATION_SCHEDULED': ['CONSULTATION_COMPLETED', 'REJECTED'],
  'CONSULTATION_COMPLETED': ['BLUEPRINT_GENERATED', 'REJECTED'],
  'BLUEPRINT_GENERATED': ['EXECUTION_IN_PROGRESS', 'REJECTED'],
  'EXECUTION_IN_PROGRESS': ['DISBURSED', 'REFINANCE_REVIEW', 'REJECTED'],
  'DISBURSED': ['REFINANCE_REVIEW', 'RETENTION_STAGE', 'MARKETPLACE_ELIGIBLE'],
  'REFINANCE_REVIEW': ['EXECUTION_IN_PROGRESS', 'RETENTION_STAGE'],
  'RETENTION_STAGE': ['MARKETPLACE_ELIGIBLE', 'REFINANCE_REVIEW'],
  'MARKETPLACE_ELIGIBLE': ['RETENTION_STAGE'],
  'REJECTED': ['NEW_LEAD'],
};

export const VALID_LIFECYCLE_TRANSITIONS: Record<CustomerLifecycleState, CustomerLifecycleState[]> = {
  'NEW_ENQUIRY': ['HIGH_STRESS_CUSTOMER', 'CONSULTATION_ACTIVE'],
  'HIGH_STRESS_CUSTOMER': ['CONSULTATION_ACTIVE', 'RETENTION_RISK'],
  'CONSULTATION_ACTIVE': ['BLUEPRINT_IN_PROGRESS', 'RETENTION_RISK'],
  'BLUEPRINT_IN_PROGRESS': ['EXECUTION_STAGE', 'RETENTION_RISK'],
  'EXECUTION_STAGE': ['REFINANCE_CANDIDATE', 'MARKETPLACE_ELIGIBLE', 'LONG_TERM_RELATIONSHIP'],
  'REFINANCE_CANDIDATE': ['EXECUTION_STAGE', 'RETENTION_RISK'],
  'RETENTION_RISK': ['CONSULTATION_ACTIVE', 'LONG_TERM_RELATIONSHIP'],
  'MARKETPLACE_ELIGIBLE': ['EXECUTION_STAGE', 'LONG_TERM_RELATIONSHIP'],
  'LONG_TERM_RELATIONSHIP': ['REFINANCE_CANDIDATE', 'RETENTION_RISK'],
};

export class GovernanceEngine {
  public static isValidLeadTransition(from: LeadStatus, to: LeadStatus): boolean {
    const allowed = VALID_LEAD_TRANSITIONS[from] || [];
    return allowed.includes(to);
  }

  public static isValidLifecycleTransition(from: CustomerLifecycleState, to: CustomerLifecycleState): boolean {
    const allowed = VALID_LIFECYCLE_TRANSITIONS[from] || [];
    return allowed.includes(to);
  }
}
